### ISSUE TITLE
DEFAULT_MENU.txt does not initalize location=12 for every mode

### ISSUE THREAD

**Issue by roeoender** [LK8000/LK8000#1131]
All modes reset unused locations except for location=12. When someone adds button at this location for default mode it won't disappear when different button - like Nav is pressed. Solution is to add sections like this:
```
mode=Config2
type=key
data=13
label= 
event=Null
location=12
```
for all modes.

BTW header in this file nor documentation doesn't mention that user configuration file should have XCI extension.

**Comment by pventafridda** [comment]
that's because there haven't been user changing this file in 7 years. Our users are not software engineers.. We have kept all options available in case things require special configurations but so far it was never requested. Initially this file was an internal resource not even available on the file system.I moved it to file system years ago in order to save precious memory in windows ce limited 32M space. It is possible that it comes back internal and no more on the file system. This in fact would solve rollback problems when changing lk versions.

**Comment by roeoender** [comment]
Hi, I found this problem when used this file to add System Setup button right in the first menu (I use setup so often that it is more convenient to have it here). I can provide patch / pull request for this file If you want.

It could also be convenient to use this file for experimental config like custom colors of snail trail.

External config file is convenient for "power users" - it would be nice to be able to setup more options with it - like things visible on standard navbars.

Regards,
Jarek Wosik

**Comment by brunotl** [comment]
changing menu file is only a workaround for bug in menu managment.
