### ISSUE TITLE
CpuLoad don't work on linux.

### ISSUE THREAD

**Issue by brunotl** [LK8000/LK8000#600]
we can see value upper than 130% on kobo

"getloadavg" report number of processes in the system run queue. it's not cpu load.
cf man page: http://linux.die.net/man/3/getloadavg

**Comment by pventafridda** [comment]
I know perfectly. It is intentional and for me it is correct.
Load average is about system load, not process load. If the system is hung because of another process, it does not matter if LK is using only 10% if the system is overloaded.
We must show system load, and this is the most effective and simple way of doing it, at system level. 130% means system is busy for sure.
Run queue is not total number of processes. See on linux “uptime” .


From: Bruno de Lacheisserie 
Sent: Wednesday, February 25, 2015 10:17 PM
To: LK8000/LK8000 
Subject: [LK8000] CpuLoad don't work on linux. (#600)

we can see value upper than 130% on kobo

"getloadavg" report number of processes in the system run queue. it's not cpu load.
cf man page: http://linux.die.net/man/3/getloadavg

**Comment by pventafridda** [comment]
If 130 is wrong, then the number of CPU cores in kobo is more than 1, but HaveSystemInfo did not detected and assumed only 1.
See function CpuSummary()


From: Bruno de Lacheisserie 
Sent: Wednesday, February 25, 2015 10:17 PM
To: LK8000/LK8000 
Subject: [LK8000] CpuLoad don't work on linux. (#600)

we can see value upper than 130% on kobo

"getloadavg" report number of processes in the system run queue. it's not cpu load.
cf man page: http://linux.die.net/man/3/getloadavg

**Comment by brunotl** [comment]
Kobo cpu is : ARM Cortex A8 800 MHz single-core Freescale MCIMX507CVM8B
