### ISSUE TITLE
Portrait mode  Infopages 2.x and 3.x need improvements

### ISSUE THREAD

**Issue by SergioDaSilva82** [LK8000/LK8000#613]
Columns are too close, is hard to read the information.

Tested with Demo maps, demo airspaces and demo waypoints.

**Comment by pventafridda** [comment]
Fixing in the weekend

From: SergioDaSilva82 
Sent: Saturday, February 28, 2015 4:14 AM
To: LK8000/LK8000 
Subject: [LK8000] Kobo: Infopages 2.x and 3.x need improvements (#613)

Columns are too close, is hard to read the information.

Tested with Demo maps, demo airspaces and demo waypoints.

**Comment by SergioDaSilva82** [comment]
Do you think 1.x info pages also need some adjustments?

**Comment by pventafridda** [comment]
no
---
Paolo Ventafridda
Sent from Samsung mobile



Il 28 Febbraio 2015 11:57:16 SergioDaSilva82 <notifications@github.com> ha 
scritto:

**Comment by pventafridda** [comment]
OK the problem is that in the west world we write text horizontally and paint it like that.
With a portrait mode screen, there is no space for all informations if we enlarge the fonts.
I can change the way LK manage informations in portrait mode, but it is not a fast change and I am not sure we have to do it in 5.4.
I think about it today


From: SergioDaSilva82 
Sent: Saturday, February 28, 2015 4:14 AM
To: LK8000/LK8000 
Subject: [LK8000] Kobo: Infopages 2.x and 3.x need improvements (#613)

Columns are too close, is hard to read the information.

Tested with Demo maps, demo airspaces and demo waypoints.

**Comment by SergioDaSilva82** [comment]
what do you think to have something like Android cellphones, the option to have small, normal or large fonts?

**Comment by pventafridda** [comment]
I am not interested to spend weeks or months to do a revolution on fonts, sergio.

**Comment by pventafridda** [comment]
Now that fonts are rendered correctly I can rework the portrait mode to make it better.
It is in my queue officially. This is going to be available for kobo first.
