### ISSUE TITLE
Canvas DrawText  crashes

### ISSUE THREAD

**Issue by pventafridda** [LK8000/LK8000#627]
Passing unusual text, this function is crashing

**Comment by brunotl** [comment]
in debug mode, if text contains invalid utf8 characters, assert is triggered.

the bug is not in DrawText, is in text source, invalid text can in very limited case :
  - invalid cast 
  - memory overflow or unterminated string
  - unchecked user input 

in all case bug need to be fixed at the source ...

**Comment by pventafridda** [comment]
I know , I have found the problem. I remove the issue.
