### ISSUE TITLE
Support ISO 8859 or go back to UNICODE

### ISSUE THREAD

**Issue by pventafridda** [LK8000/LK8000#676]
Loading text from a file written on a PC (the standard) or importing a waypoint file, a notepad file, anything like a text file, will not necessarily be encoded in UTF8. 
In such case the current implementation from xcs will miserably crash after useless assertions.

**Comment by brunotl** [comment]
I Will fix that when i'm back

Le 24 mai 2015 à 02:27, Paolo Ventafridda <notifications@github.com> a
écrit :

Loading text from a file written on a PC (the standard) or importing a
waypoint file, a notepad file, anything like a text file, will not
necessarily be encoded in UTF8.
In such case the current implementation from xcs will miserably crash after
useless assertions.

—
Reply to this email directly or view it on GitHub
<https://github.com/LK8000/LK8000/issues/676>.

**Comment by pventafridda** [comment]
Great thanks. If you agree, I would at the same time fix the xcs code (like we did for freetype) because it is unacceptable that we have a crash only because of a malformed waypoint file (for example).
I also would much prefer that such cases are not going under the useless "DEBUG" mode, which works only when you can replicate the problem! 
So my intention is to redefine assert into LKASSERT which requires LKAssert.h to be added to the xcs code.

**Comment by brunotl** [comment]
Don't do that please !!!

Le 24 mai 2015 à 15:24, Paolo Ventafridda <notifications@github.com> a
écrit :

Great thanks. If you agree, I would at the same time fix the xcs code (like
we did for freetype) because it is unacceptable that we have a crash only
because of a malformed waypoint file (for example).
I also would much prefer that such cases are not going under the useless
"DEBUG" mode, which works only when you can replicate the problem!
So my intention is to redefine assert into LKASSERT which requires
LKAssert.h to be added to the xcs code.

—
Reply to this email directly or view it on GitHub
<https://github.com/LK8000/LK8000/issues/676#issuecomment-105016319>.

**Comment by pventafridda** [comment]
Ok
---
Sent from mobile



Il 27 Maggio 2015 09:02:22 Bruno de Lacheisserie <notifications@github.com> 
ha scritto:
